AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-ts-test
Globals:
  Function:
    Timeout: 3

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: built/
      Handler: app.handler
      Runtime: nodejs16.x
      Events:
        TestEvent:
          Type: Api 
          Properties:
            Path: /hello
            Method: get